# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8dbf405d4fe571fbe60a17cac44f9ed9cc5804ffed2d333b490b5e8e8161886d931277db86f5acd8e59ae652c2a859d55c668f32065a83732729119c12f255cd

test:
  secret_key_base: d2d494db0103a75f0cbb8fcc0f707798cdb8cfc4bb179f6ac369b6168275aafdabc57d345679fadfe22ee9feb5f602c8312ae9e0c66f15f1760232f6b50dca9a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
